### ISSUE TITLE
Aesthetics of Chord plot

### ISSUE THREAD

**Issue by AltayYuzeir** [enblacar/SCpubr-book#1]
Hello, 
First, I want to say thank you for the awesome work you are doing with SCpubr! 
And the integration with LIANA is just awesome idea!

I have been working on CCC pipeline using both LIANA and SCpubr. I have few aesthetic questions about the chord diagrams.
1. And is it possible to reduce the fontsize of the labels and make the sections thinner (image below)?
2. Is it possible to increase the size of the center plot and somehow improve the long labels?
3. I have also noticed the default setting Chord plots produce quite different results, compared to the Chord plots in the tutorial at https://enblacar.github.io/SCpubr-book/ligand-receptor-analysis.html#compute-chord-diagrams-of-the-interactions
4. Is it possible to make the transparency as function of Interaction specificity, similarly to NicheNet.

In any case, thanks a lot!

<img width="493" alt="Capture" src="https://user-images.githubusercontent.com/34285813/195018069-ebddb649-8f56-49d8-af6c-632f9939edb2.PNG">

![unnamed-chunk-27-1](https://user-images.githubusercontent.com/34285813/194893701-ff69514d-8748-4fb1-b3c7-bb1dc49acb2b.png)

**Comment by enblacar** [comment]
Hi @AltayYuzeir,

Thanks a lot! It's really nice that people find this package useful!

Indeed, I also experienced this change in the chord diagram plots, that they became smaller. I might still need to do some more tweaks!

Regarding your comments:
- The chord diagrams outputted by `SCpubr::do_LigandReceptorPlot()` are an optimized version of the ones returned by `SCpubr::do_ChordDiagramPlot()`.  This way, I am setting the parameters myself, allowing little customization, and this is a design choice.  For a free customization, please use `SCpubr::do_ChordDiagramPlot()`.
- Regarding the size of the chord diagram, I will have a deeper look into it! It was already in my to-do list!
- It's a very nice idea to use the specificity with the alpha. However, these diagrams show the relationship of ligand-receptor as an average between all the possible interactions taking place. So its implementation might take a while. I will put it on the To-Do list!

However, since this is a side project apart from my PhD, it might take some time for this to be implemented!

Thanks for reaching out and for similar issues/implementations/enhancements, could you please open the issue in the [main GitHub repo of the package](https://github.com/enblacar/SCpubr)?

**Comment by AltayYuzeir** [comment]
I see. Thank you for your extensive feedback. I will close this issue now.
